### ISSUE TITLE
super cool i wanna try 

### ISSUE THREAD

**Issue by rossman22590** [ttio2tech/voice-assistant-openaiapi#1]
Failed to compile
node:async_hooks
Module build failed: UnhandledSchemeError: Reading from "node:async_hooks" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.

**Comment by ttio2tech** [comment]
what os are using? Node version?    I tested on Ubuntu 22.04 and no issues to compile.

**Comment by ttio2tech** [comment]
The issue seems to because of a package that uses async_hooks on client side. However it works fine on Ubuntu. I have updated the repo. Please try it again! Sorry about the inconvenience. @rossman22590
